In [1]:
import numpy as np

# Creating matrices
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

# Matrix addition
C = A + B
print("Matrix Addition:")
print(C)

# Matrix subtraction
D = A - B
print("\nMatrix Subtraction:")
print(D)

# Matrix multiplication
E = np.dot(A, B)
print("\nMatrix Multiplication:")
print(E)

# Transpose of a matrix
F = A.T
print("\nMatrix Transpose:")
print(F)

# Eigenvalues and eigenvectors of a matrix
eigenvalues, eigenvectors = np.linalg.eig(A)
print("\nEigenvalues of Matrix A:")
print(eigenvalues)
print("\nEigenvectors of Matrix A:")
print(eigenvectors)

# Calculate correlation matrix
correlation_matrix = np.corrcoef(A.T)
print("\nCorrelation Matrix:")
print(correlation_matrix)


Matrix Addition:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Matrix Subtraction:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

Matrix Multiplication:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Matrix Transpose:
[[1 4 7]
 [2 5 8]
 [3 6 9]]

Eigenvalues of Matrix A:
[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]

Eigenvectors of Matrix A:
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]

Correlation Matrix:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
