In [6]:
import numpy as np
import pandas as pd
from sklearn.feature_selection import SelectKBest, f_regression
from sklearn.preprocessing import PolynomialFeatures

# Feature Generation

# Create a sample dataset
X = np.array([[1, 2],
              [3, 4],
              [5, 6]])

# Polynomial Features
poly = PolynomialFeatures(degree=2)
X_poly = poly.fit_transform(X)

print("Polynomial Features:")
print(X_poly)

# Feature Selection

# Create a sample dataset
data = {
    'Feature1': [1, 2, 3, 4, 5],
    'Feature2': [6, 7, 8, 9, 10],
    'Target': [11, 12, 13, 14, 15]
}
df = pd.DataFrame(data)

# Separate features and target
X = df[['Feature1', 'Feature2']]
y = df['Target']

# SelectKBest with f_regression
selector = SelectKBest(score_func=f_regression, k=1)
X_new = selector.fit_transform(X, y)

print("\nFeature Selection:")
print("Selected Features:")
print(X.columns[selector.get_support()])



Polynomial Features:
[[ 1.  1.  2.  1.  2.  4.]
 [ 1.  3.  4.  9. 12. 16.]
 [ 1.  5.  6. 25. 30. 36.]]

Feature Selection:
Selected Features:
Index(['Feature2'], dtype='object')
