Name:- Anagh Garg
Reg.no :- 20BAI10127

In [ ]:
#1
x = 10+2j
y = 7+9j
#Addition
print(x+y)
#Subtraction
print(x-y)
#Multiplication
print(x*y)
#Check if equal
if(x.real==y.real):
  print("Equal")
elif(x.real>y.real):
  print("x is greater than y")
else:
  print("y is greater than x")

(17+11j)
(3-7j)
(52+104j)
x is greater than y


In [ ]:
#2
class Circle():
    def __init__(self, r):
        self.radius = r

    def area_circle(self):
        return self.radius**2*3.14
    
    def perimeter_circle(self):
        return 2*self.radius*3.14

New_circle = Circle(5)
print(New_circle.area_circle())
print(New_circle.perimeter_circle())

78.5
31.400000000000002


In [ ]:
#3
class Rectangle():
    def __init__(self, l, w):
        self.length = l
        self.width  = w

    def area_rect(self):
        return self.length*self.width

In [ ]:
#4 

class Address:
	def _init_(self, street_name, number):
		self.street_name = street_name
		self.number = number

In [ ]:
#5

class bikes:
  def _init_(self, model, colour):
    self.model = model
    self.colour = colour

class Yamaha(bikes):
  def _init_(self, year, make):
    self.year = year
    self.make = make

class Bullet(bikes):
  def _init_(self, year, make):
    self.year = year
    self.make = make

class Hero_honda(bikes):
  def _init_(self, year, make):
    self.year = year
    self.make = make

In [ ]:
#6

class Person:
    def __init__(self, name, valid_id):
        self.name = name
        self.valid_id = valid_id
    def print(self):
        print(f'\nName: {self.name}')
        print(f'Valid ID: {self.valid_id}')
class Student(Person):
    def __init__(self, name, valid_id, age):
        super().__init__(name, valid_id)
        self.age = age
    def print(self):
        super().print()  
        print(f'Age: {self.age}')
    def change_age(self, age):
        self.age = age
    def change_name(self, name):
        self.name = name
    
# Driver Code
student = Student("Anagh Garg", "20BAI10127", "20")
student.print()
student.change_age(20)
student.change_name("Hamza")
student.print()




Name: Anagh Garg
Valid ID: 20BAI10127
Age: 20

Name: Hamza
Valid ID: 20BAI10127
Age: 20


In [ ]:
#7

class Student:
    school = 'NMIMS'
    address = 'Mumbai' 

#student 1

student1 = Student()
student1.student_name = "Kartikeya Srivastava"
student1.student_id = "24-CY-098"
student1.marks_Marathi = 100
student1.marks_Social_Science = 56
student1.marks_English = 78


#student 2
student2 = Student() 
student2.student_name = "Vaishnavi Jha"
student2.student_id = "23-AI-125"
student2.marks_Marathi = 94
student2.marks_Social_Science = 91
student2.marks_English = 80
students = [student1, student2]
for student in students:
    print('\n')
    for attr in student.__dict__:
        print(f'{attr} -> {getattr(student, attr)}')



student_name -> Kartikeya Srivastava
student_id -> 24-CY-098
marks_Marathi -> 100
marks_Social_Science -> 56
marks_English -> 78


student_name -> Vaishnavi Jha
student_id -> 23-AI-125
marks_Marathi -> 94
marks_Social_Science -> 91
marks_English -> 80


In [ ]:
#8
class Animal:
    def __init__(self, type, name, color, age):
        self.type = type
        self.name = name
        self.color = color
        self.age = age
    def print(self):
        print(f'Type: {self.type}, Name: {self.name}, Color: {self.color}, Age: {self.age}')
    
class Horse(Animal):
    pass
class Cow(Animal):
    pass
class Sheep(Animal):
    pass
horse = Horse("Domestic", "Horse", "Black", 12)
horse.print()
cow = Cow("Domestic", "Cow", "White", 5)
cow.print()


Type: Domestic, Name: Horse, Color: Black, Age: 12
Type: Domestic, Name: Cow, Color: White, Age: 5


In [ ]:
#9

class Test:
  def __init__(self):
    self.x = 1
  def x_value(self):
    self.x = 10
  
class Test_derived(Test):
  def x_value(self):
    self.x=self.x+1
    return self.x
    
def main():
  obj = Test_derived()
  print(obj.x_value())
main()

2


In [ ]:
#10
import numpy as np
#1st matrix
A = np.array([[7, 3], [23, 5]])
  
#2nd matrix
B = np.array([[1, 9], [23, 24]])
  
print("Printing elements of 1st matrix")
print(A)
print("Printing elements of 2nd matrix")
print(B)
  
# adding 
print("Addition of two matrix")
print(np.add(A, B))

# subtracting 
print("Subtraction of two matrix")
print(np.subtract(A, B))

# multiplying 
print("Multiplcation of two matrix")
print(np.multiply(A, B))



Printing elements of 1st matrix
[[ 7  3]
 [23  5]]
Printing elements of 2nd matrix
[[ 1  9]
 [23 24]]
Addition of two matrix
[[ 8 12]
 [46 29]]
Subtraction of two matrix
[[  6  -6]
 [  0 -19]]
Multiplcation of two matrix
[[  7  27]
 [529 120]]


In [ ]:
#11


fruit_set = set()
fruit_set.add("Banana")
print(fruit_set)
fruit_set.update(["Apple","Mango"])
print(fruit_set)

{'Banana'}
{'Banana', 'Mango', 'Apple'}


In [ ]:
#12

num_set =set([0,1,3,4,5])
print("All elements in set:")
print(num_set)
print("\nRemove 3 from set:")
num_set.discard(3)
print(num_set)

All elements in set:
{0, 1, 3, 4, 5}

Remove 3 from set:
{0, 1, 4, 5}


In [ ]:
#13

def multiply(z):

    a = 1

    for k in z:

        a*= k

    return a

list=[11,22,14,79,102]

print(multiply (list))

27300504


In [ ]:
#14

Number_list = [10,2,3,6,8,89,25,264]
 
Number_list.sort()
 

print("Largest element is:", *Number_list[7:8])

Largest element is: 264


In [ ]:
  #15

Number_list = [10,2,3,6,8,89,25,264]
 
Number_list.sort()
 

print("Smallest element is:", *Number_list[0:1])

Smallest element is: 2
