In [3]:
import numpy as np
from sklearn.decomposition import PCA

# Create a sample matrix
X = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10, 11, 12]])

# Singular Value Decomposition (SVD)
U, S, V = np.linalg.svd(X, full_matrices=False)

print("Singular Value Decomposition (SVD):")
print("U:")
print(U)
print("S:")
print(np.diag(S))
print("V:")
print(V)

# Principal Component Analysis (PCA)
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X)

print("\nPrincipal Component Analysis (PCA):")
print("Explained Variance Ratio:")
print(pca.explained_variance_ratio_)
print("Principal Components:")
print(X_pca)


Singular Value Decomposition (SVD):
U:
[[-0.14087668 -0.82471435  0.53999635]
 [-0.34394629 -0.42626394 -0.65166613]
 [-0.54701591 -0.02781353 -0.31665681]
 [-0.75008553  0.37063688  0.42832658]]
S:
[[2.54624074e+01 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.29066168e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 2.40694596e-15]]
V:
[[-0.50453315 -0.5745157  -0.64449826]
 [ 0.76077568  0.05714052 -0.64649464]
 [-0.40824829  0.81649658 -0.40824829]]

Principal Component Analysis (PCA):
Explained Variance Ratio:
[1. 0.]
Principal Components:
[[-7.79422863  0.        ]
 [-2.59807621  0.        ]
 [ 2.59807621  0.        ]
 [ 7.79422863 -0.        ]]
